apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/myuser/helm-charts
    path: charts/myapp
    targetRevision: HEAD
    helm:
      releaseName: myapp
      values: |
        replicaCount: 3
        image:
          repository: myregistry/myapp
          tag: v1.0.0
          pullPolicy: IfNotPresent
        service:
          type: LoadBalancer
          port: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

