# Filebeat Configuration

filebeat.inputs:
  # System logs
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /var/log/messages
      - /var/log/syslog
    fields:
      log_type: system
      environment: production
    fields_under_root: true

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    fields:
      log_type: docker
    fields_under_root: true

# Filebeat modules (commented out, enable as needed)
# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false

# Processors to enrich data
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Output to Logstash
output.logstash:
  hosts: ["${LOGSTASH_HOSTS:logstash:5044}"]
  bulk_max_size: 1024
  compression_level: 3

# Alternative: Output directly to Elasticsearch (uncomment to use)
# output.elasticsearch:
#   hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]
#   indices:
#     - index: "filebeat-system-%{+yyyy.MM.dd}"
#       when.equals:
#         fields.log_type: "system"
#     - index: "filebeat-docker-%{+yyyy.MM.dd}"
#       when.equals:
#         fields.log_type: "docker"

# Setup Kibana dashboards (optional)
setup.kibana:
  host: "${KIBANA_HOST:kibana:5601}"

# Index lifecycle management
setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Internal queue settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s

