name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Update deployment image
        run: |
          kubectl set image deployment/my-app \
            my-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -n ${{ env.K8S_NAMESPACE }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/my-app \
            -n ${{ env.K8S_NAMESPACE }} \
            --timeout=5m

      - name: Verify deployment
        run: |
          kubectl get deployment my-app -n ${{ env.K8S_NAMESPACE }}
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=my-app

      - name: Run smoke tests
        run: |
          # Add your smoke tests here
          echo "Running smoke tests..."
          # kubectl exec -it <pod> -- curl http://localhost:8080/health

      - name: Rollback on failure
        if: failure()
        run: |
          kubectl rollout undo deployment/my-app -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/my-app -n ${{ env.K8S_NAMESPACE }}

      - name: Notify deployment
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Kubernetes Deployment
            Environment: ${{ github.event.inputs.environment || 'staging' }}
            Status: ${{ job.status }}
            Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

